### PR TITLE
FOGL-2836 make release default 1

### PR DESCRIPTION
**Pull request by MarkRiddoch**

### CODE REVIEW

**Review by ashish-jabble — CHANGES_REQUESTED** [review]
Below error with this change
```
[ec2-user@ip-10-0-0-170 foglamp-pkg]$ ./make_rpm 
The package root directory is : /home/ec2-user/foglamp-pkg
The FogLAMP directory is      : /usr/local/foglamp/
The FogLAMP version is        : 1.5.2
The package will be built in  : /home/ec2-user/foglamp-pkg/packages/rpmbuild/RPMS/x86_64
The package name is           : foglamp-1.5.2-0.00.x86_64

Populating the package and updating version in control file...Done.
Prepare data directory
Building the new package...
Processing files: foglamp-1.5.2-1.x86_64
error: File not found by glob: /home/ec2-user/foglamp-pkg/packages/rpmbuild/BUILDROOT/foglamp-1.5.2-1.x86_64/usr/local/*


RPM build errors:
    File not found by glob: /home/ec2-user/foglamp-pkg/packages/rpmbuild/BUILDROOT/foglamp-1.5.2-1.x86_64/usr/local/*

```
You need to fix below files as well
1) `make_rpm` script
```
+package_name="${pkg_name}-${version}-1.${architecture}"
```
2) Fix README.rst O/p logs
3) Also please add below in .gitignore file
```
!/packages/rpmbuild/SPECS
```

**Comment by MarkRiddoch** [comment]
The first issue is because of the way @sstefano69 did the make_rpm, it does not build from source but expects a make install has been run previously. There is already an outstanding Jira to resolve this.

I am not sure why you want this added to .gitignore, what is the problem you are seeing?

**Comment by ashish-jabble** [comment]
> I am not sure why you want this added to .gitignore, what is the problem you are seeing?

We usually  build specific files are git ignored those are not expected to push and even not listed as untracked files.

Also, as everything is stored under `rpmbuild` which is not correct for the RPM build, it should be like as below
```
RPM
├── build (build related files under this dir)
└── SPECS
    └── foglamp.spec
```
We will take this as a separate improvements. Hence approved.

**Review by ashish-jabble — DISMISSED** [review]

**Review by ashish-jabble — APPROVED** [review]
Now LGTM!! Also for RPM package summary we have added package name in text.

**Pull request merged**
