### PR TITLE
FOGL-2808: rpm build from source, working stage / initial version

### PR DESCRIPTION
**Pull request by sstefano69**
tested : 
* Centos
* RHEl 7.6

test : 
```
cd ~;\
rm -rf ~/foglamp-pkg;\
sudo yum install -y git;\
git clone -b FOGL-2808 https://github.com/foglamp/foglamp-pkg.git;\
cd ~/foglamp-pkg;\
./make_rpm -h;\
export FOGLAMP_ROOT="";\
echo "DBG FOGLAMP_ROOT :${FOGLAMP_ROOT}:";\
cd  ~/foglamp-pkg;\
time ./make_rpm -b FOGL-2808
```

image

### CODE REVIEW

**Review by pintomax — DISMISSED** [review]
LGTM

**Review by AmandeepArora — COMMENTED** [review]
Looks good.

**Review by MarkRiddoch — APPROVED** [review]
Looks ok to me

**Comment by ashish-jabble** [comment]
@sstefano69 Before pressing the merge button for this repo, please be in synch with _CI_ maintainer @Singhal-Vaibhav or with me. As this repo has dependent on CI work as well.
cc/ @MarkRiddoch

**Pull request merged**
