### PR TITLE
FOGL-2839 requirements should not be run as root

### PR DESCRIPTION
**Pull request by MarkRiddoch**
Note some requirements.sh scripts may need to be modified to include sudo on individual commands

### CODE REVIEW

**Review by pintomax — APPROVED** [review]

**Comment by ashish-jabble** [comment]
It seems to be we need another exercise to add `sudo` command for apt/yum package in requirements.sh for approx 60+ repos (i.e plugins one)

**Comment by MarkRiddoch** [comment]
> It seems to be we need another exercise to add `sudo` command for apt/yum package in requirements.sh for approx 60+ repos (i.e plugins one)

They should have already been there. However looking at the list, 
foglamp-notify-alexa-notifyme/requirements.sh:
foglamp-notify-blynk/requirements.sh:
foglamp-notify-email/requirements.sh:
foglamp-notify-google-hangouts/requirements.sh:
foglamp-notify-ifttt/requirements.sh:
foglamp-notify-telegram/requirements.sh:

It is only very few that need any attention.

These have now be updated.

**Review by ashish-jabble — APPROVED** [review]
Assuming that `sudo` has been updated for all repos. Hence approved.

**Comment by ashish-jabble** [comment]
How about modbus-c plugin changes? https://github.com/foglamp/foglamp-south-modbus-c/blob/develop/requirements.sh. Also please fix typo in https://github.com/foglamp/foglamp-notify-blynk/pull/10/files#diff-a17370e1077809f0c02d540f79f2a8eeR31

**Pull request merged**
